<?php

return [
    'ldap' => [
        'enabled' => false,
        'account_suffix' => '@gatech.edu',
        'domain_controllers' => ['whitepages.gatech.edu'],
        'base_dn' => 'dc=whitepages,dc=gatech,dc=edu',
        'admin_username' => '',
        'admin_password' => '',
        'port' => 389,
        'follow_referrals' => false,
        'use_ssl' => false,
        'use_tls' => false,
        'use_sso' => false,
        'username_field' => 'email',
        'password_field' => 'password',
        'id_field' => '_id',
    ],
    'couchdb' => [
        'enabled' => false,
        'username_field' => 'email',
        'password_field' => 'password',
        'id_field' => '_id',
        'use_local_connection' => false,
        'couchdb_config' => [
            'database' => 'multilogin',
            'host' => 'localhost',
            'port' => 5984,
            'username' => null,
            'password' => null,
            'models_dir' => app_path().'\\Models\\',
            'lucene_handler_name' => '_fti',
            'proxies_dir' => app_path().'storage/proxies',
            'keep-alive' => true,
            'timeout' => '0.01',
            'views_folder' => '../app/couchdb',
        ],
    ],
];
